[build]
  command = "npm run build"
  publish = "build"
  functions="netlify/functions"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/shop/*"
  to = "https://your-vercel-app.vercel.app/:splat"
  status = 200
  force = true
